import "dotenv/config";
import http from "node:http";
import express from "express";
import cors from "cors";
import mongoose from "mongoose";
import { Server as SocketIOServer } from "socket.io";

const app = express();
const server = http.createServer(app);
const io = new SocketIOServer(server, {
  cors: {
    origin: process.env.CORS_ORIGIN || "*",
  },
});

const PORT = Number(process.env.PORT || 3001);
const MONGODB_URI = process.env.MONGODB_URI;
const AI_API_URL = process.env.AI_API_URL;
const AI_API_KEY = process.env.AI_API_KEY;
const AI_MODEL = process.env.AI_MODEL || "gpt-4.1-mini";

app.use(cors());
app.use(express.json({ limit: "1mb" }));

const chatMessageSchema = new mongoose.Schema(
  {
    roomId: { type: String, required: true, index: true },
    user: { type: String, required: true, trim: true },
    text: { type: String, required: true, trim: true },
    userId: { type: String, default: "guest" },
    initials: { type: String, default: "US" },
  },
  { timestamps: true },
);

const ChatMessage = mongoose.model("ChatMessage", chatMessageSchema);

const mongoReadyState = () => mongoose.connection.readyState === 1;

const maybeConnectMongo = async () => {
  if (!MONGODB_URI) {
    console.warn("[backend] MONGODB_URI missing. Running without MongoDB persistence.");
    return;
  }

  try {
    await mongoose.connect(MONGODB_URI, {
      serverSelectionTimeoutMS: 5000,
    });
    console.log("[backend] MongoDB connected");
  } catch (error) {
    console.error("[backend] MongoDB connection failed, continuing without DB:", error.message);
  }
};

const clamp = (value, min, max) => Math.min(max, Math.max(min, value));

const buildAiPrompt = ({ prompt, systemPrompt }) => {
  const messages = [];
  if (systemPrompt) {
    messages.push({ role: "system", content: systemPrompt });
  }
  messages.push({ role: "user", content: prompt });
  return messages;
};

const callAiProvider = async ({ prompt, systemPrompt = "", model, temperature = 0.7 }) => {
  if (!AI_API_URL || !AI_API_KEY) {
    return {
      text: `Mock AI response: ${prompt.slice(0, 120)}`,
      provider: "mock",
      model: model || "mock-model",
    };
  }

  const response = await fetch(AI_API_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${AI_API_KEY}`,
    },
    body: JSON.stringify({
      model: model || AI_MODEL,
      temperature: clamp(Number(temperature) || 0.7, 0, 1),
      messages: buildAiPrompt({ prompt, systemPrompt }),
    }),
  });

  if (!response.ok) {
    const detail = await response.text();
    throw new Error(`AI API failed: ${response.status} ${detail}`);
  }

  const data = await response.json();
  const text = data?.choices?.[0]?.message?.content || data?.output_text || "";
  return {
    text: text || "No response generated by AI provider.",
    provider: "external",
    model: data?.model || model || AI_MODEL,
  };
};

const toClientMessage = (message) => ({
  id: String(message._id || message.id || Date.now()),
  roomId: message.roomId,
  user: message.user,
  text: message.text,
  userId: message.userId || "guest",
  initials: message.initials || "US",
  isOwn: false,
  time: new Date(message.createdAt || Date.now()).toLocaleTimeString([], {
    hour: "2-digit",
    minute: "2-digit",
  }),
});

app.get("/api/health", (_req, res) => {
  res.json({
    ok: true,
    service: "quantam-backend",
    mongoConnected: mongoReadyState(),
    socketClients: io.engine.clientsCount,
  });
});

app.get("/api/chat/rooms/:roomId/messages", async (req, res) => {
  const roomId = String(req.params.roomId || "").trim();
  const limit = clamp(Number(req.query.limit) || 50, 1, 200);
  if (!roomId) {
    return res.status(400).json({ error: "roomId is required" });
  }

  if (!mongoReadyState()) {
    return res.json({ roomId, messages: [] });
  }

  const messages = await ChatMessage.find({ roomId }).sort({ createdAt: -1 }).limit(limit).lean();
  return res.json({
    roomId,
    messages: messages.reverse().map(toClientMessage),
  });
});

app.post("/api/ai/generate", async (req, res) => {
  const mode = req.body?.mode === "image" ? "image" : "text";
  const prompt = String(req.body?.prompt || "").trim();
  const model = req.body?.model ? String(req.body.model) : undefined;
  const systemPrompt = String(req.body?.systemPrompt || "");
  const temperature = req.body?.temperature;

  if (!prompt) {
    return res.status(400).json({ error: "prompt is required" });
  }

  try {
    if (mode === "image") {
      return res.json({
        mode,
        result: "Image generation endpoint wired. Configure your image provider in backend for live outputs.",
      });
    }

    const ai = await callAiProvider({ prompt, systemPrompt, model, temperature });
    return res.json({ mode, result: ai.text, provider: ai.provider, model: ai.model });
  } catch (error) {
    return res.status(502).json({ error: "AI request failed", detail: error.message });
  }
});

io.on("connection", (socket) => {
  socket.on("chat:join", ({ roomId }) => {
    const safeRoomId = String(roomId || "").trim();
    if (!safeRoomId) return;
    socket.join(safeRoomId);
  });

  socket.on("chat:send", async (payload = {}) => {
    const roomId = String(payload.roomId || "").trim();
    const text = String(payload.text || "").trim().slice(0, 2000);
    const user = String(payload.user || "You").trim().slice(0, 40);
    const userId = String(payload.userId || "you").trim().slice(0, 80);
    const initials = String(payload.initials || "YO").trim().slice(0, 5).toUpperCase();

    if (!roomId || !text) return;

    let created = {
      id: String(Date.now()),
      roomId,
      user,
      text,
      userId,
      initials,
      createdAt: new Date(),
    };

    if (mongoReadyState()) {
      const saved = await ChatMessage.create({ roomId, text, user, userId, initials });
      created = saved.toObject();
    }

    io.to(roomId).emit("chat:message", toClientMessage(created));
  });

  socket.on("ai:generate", async (payload = {}) => {
    const prompt = String(payload.prompt || "").trim();
    if (!prompt) {
      socket.emit("ai:error", { error: "prompt is required" });
      return;
    }

    try {
      const result = await callAiProvider({
        prompt,
        systemPrompt: String(payload.systemPrompt || ""),
        model: payload.model ? String(payload.model) : undefined,
        temperature: payload.temperature,
      });
      socket.emit("ai:response", { result: result.text, model: result.model, provider: result.provider });
    } catch (error) {
      socket.emit("ai:error", { error: "AI request failed", detail: error.message });
    }
  });
});

await maybeConnectMongo();

server.listen(PORT, () => {
  console.log(`[backend] Server listening on http://localhost:${PORT}`);
});
